import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, Link, useSearchParams } from "react-router-dom";
import { Loader2, ArrowLeft, Mail, Eye, EyeOff, ShieldAlert, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { validatePasswordPair, MIN_PASSWORD_LENGTH } from "@/lib/passwordRules";
import { initialUrlHashParams, initialUrlSearchParams } from "@/lib/authUrlSnapshot";
import owlMascot from "@/assets/owl-mascot.png";

type Mode = "request" | "recover" | "expired" | "done";

interface RecoveryIntent {
  tokenHash: string | null;
  hasLegacyRecoveryHash: boolean;
  hasUrlError: boolean;
  hasInvalidRecoveryQuery: boolean;
}

function readRecoveryIntent(): RecoveryIntent {
  // Read the URL as it was originally delivered — supabase-js may already have
  // consumed hash tokens and rewritten the address bar to a bare `#`.
  const query = initialUrlSearchParams();
  const hash = initialUrlHashParams();
  const liveQuery = new URLSearchParams(window.location.search);
  const linkType = query.get("type") ?? hash.get("type") ?? liveQuery.get("type");
  const rawTokenHash = query.get("token_hash") ?? liveQuery.get("token_hash");

  return {
    tokenHash: rawTokenHash && linkType === "recovery" ? rawTokenHash : null,
    // A recovery redirect from the auth backend arrives with a session in the
    // hash. `type` is not always present, so treat any access/refresh token in
    // the original hash as a recovery hand-off on this screen.
    hasLegacyRecoveryHash: hash.has("access_token") || hash.has("refresh_token"),
    hasUrlError: Boolean(
      query.get("error") ??
        query.get("error_code") ??
        hash.get("error") ??
        hash.get("error_code"),
    ),
    hasInvalidRecoveryQuery: Boolean(rawTokenHash && linkType !== "recovery"),
  };
}


/**
 * Password recovery + reset-request screen.
 *
 * Recovery links generated by the branded auth email point at
 * `/auth/reset-password?token_hash=...&type=recovery`. The token is NOT
 * verified on render (email prefetch scanners would burn the single-use token)
 * — it is verified only when the student deliberately submits a new password.
 *
 * Legacy links that redirect here with a recovery session in the URL hash are
 * still supported: supabase-js hydrates the session and we simply update the
 * password without calling verifyOtp.
 */
export function ResetPasswordPage() {
  const [params, setParams] = useSearchParams();
  const { toast } = useToast();
  const navigate = useNavigate();
  // Capture recovery intent once, from THIS tab's URL. Auth sessions are
  // shared through localStorage, but a reset page must never be switched into
  // recovery mode by an event broadcast from a different tab.
  const recoveryIntentRef = useRef<RecoveryIntent>(readRecoveryIntent());
  const recoveryIntent = recoveryIntentRef.current;
  const tokenHash = recoveryIntent.tokenHash;

  const [mode, setMode] = useState<Mode>(() => {
    if (recoveryIntent.hasUrlError || recoveryIntent.hasInvalidRecoveryQuery) return "expired";
    if (tokenHash || recoveryIntent.hasLegacyRecoveryHash) return "recover";
    return "request";
  });

  // Request-a-link state
  const [email, setEmail] = useState("");
  const [isSending, setIsSending] = useState(false);
  const [isSent, setIsSent] = useState(false);

  // New-password state
  const [hasRecoverySession, setHasRecoverySession] = useState(false);
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [fieldError, setFieldError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Strip technical error params only after this tab has captured the recovery
  // intent. Keep token_hash intact until deliberate form submission.
  useEffect(() => {
    if (!recoveryIntent.hasUrlError) return;

    const next = new URLSearchParams(params);
    ["error", "error_code", "error_description"].forEach((k) => next.delete(k));
    const search = next.toString();
    window.history.replaceState(
      null,
      "",
      `${window.location.pathname}${search ? `?${search}` : ""}`,
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [recoveryIntent.hasUrlError]);

  useEffect(() => {
    if (!recoveryIntent.hasLegacyRecoveryHash) return;

    let isActive = true;
    const { data: sub } = supabase.auth.onAuthStateChange((event, session) => {
      if (isActive && event === "PASSWORD_RECOVERY" && session) {
        setHasRecoverySession(true);
      }
    });

    supabase.auth.getSession().then(({ data }) => {
      if (isActive && data.session) setHasRecoverySession(true);
    });

    return () => {
      isActive = false;
      sub.subscription.unsubscribe();
    };
  }, [recoveryIntent.hasLegacyRecoveryHash]);

  const canSubmitNewPassword = useMemo(
    () => validatePasswordPair(password, confirmPassword) === null && !isSubmitting,
    [password, confirmPassword, isSubmitting],
  );

  const handleRequest = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email) return;

    setIsSending(true);
    try {
      // Keep the student on the tenant hostname they started from.
      const { error } = await supabase.auth.resetPasswordForEmail(email.trim(), {
        redirectTo: `${window.location.origin}/auth/reset-password`,
      });
      if (error) throw error;

      setIsSent(true);
      toast({
        title: "Reset link sent",
        description: "Check your email for the password reset link.",
      });
    } catch (err) {
      toast({
        title: "We couldn't send that link",
        description: "Please check the email address and try again.",
        variant: "destructive",
      });
    } finally {
      setIsSending(false);
    }
  };

  const handleUpdatePassword = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmitting) return;

    const invalid = validatePasswordPair(password, confirmPassword);
    if (invalid) {
      setFieldError(invalid);
      return;
    }
    setFieldError(null);
    setIsSubmitting(true);

    try {
      // Verify the single-use recovery token only now — at the student's
      // deliberate action — unless a recovery session already exists.
      if (!hasRecoverySession) {
        if (!tokenHash) {
          setMode("expired");
          return;
        }
        const { error: verifyError } = await supabase.auth.verifyOtp({
          token_hash: tokenHash,
          type: "recovery",
        });
        if (verifyError) {
          setMode("expired");
          return;
        }
      }

      const { error: updateError } = await supabase.auth.updateUser({ password });
      if (updateError) {
        const message = /same/i.test(updateError.message)
          ? "Please choose a password different from your current one."
          : "We couldn't update your password. Please request a new reset link.";
        setFieldError(message);
        return;
      }

      // Clear recovery state: no stale token, no lingering recovery session.
      setPassword("");
      setConfirmPassword("");
      setHasRecoverySession(false);
      const cleaned = new URLSearchParams(params);
      ["token_hash", "type"].forEach((k) => cleaned.delete(k));
      setParams(cleaned, { replace: true });
      await supabase.auth.signOut();
      setMode("done");
    } finally {
      setIsSubmitting(false);
    }
  };

  const shell = (children: React.ReactNode) => (
    <div className="min-h-screen bg-background flex items-center justify-center p-4">
      <Card className="w-full max-w-md p-6 space-y-6 bg-card/80 backdrop-blur-sm border-border">
        {children}
      </Card>
    </div>
  );

  const backToLogin = (
    <div className="text-center">
      <Link to="/auth" className="text-sm text-accent hover:underline inline-flex items-center gap-1">
        <ArrowLeft className="w-3 h-3" />
        Back to login
      </Link>
    </div>
  );

  // ── Expired / invalid recovery link ──────────────────────────────────────
  if (mode === "expired") {
    return shell(
      <>
        <div className="text-center space-y-3">
          <div className="w-16 h-16 mx-auto rounded-full bg-destructive/10 flex items-center justify-center">
            <ShieldAlert className="w-8 h-8 text-destructive" />
          </div>
          <h1 className="text-2xl font-bold text-foreground">Reset link expired</h1>
          <p className="text-muted-foreground text-sm">
            This password reset link is no longer valid. Request a new link to continue.
          </p>
        </div>
        <Button
          className="w-full"
          onClick={() => {
            setIsSent(false);
            setMode("request");
          }}
        >
          Send a new reset link
        </Button>
        {backToLogin}
      </>,
    );
  }

  // ── Success ──────────────────────────────────────────────────────────────
  if (mode === "done") {
    return shell(
      <>
        <div className="text-center space-y-3">
          <div className="w-16 h-16 mx-auto rounded-full bg-accent/10 flex items-center justify-center">
            <CheckCircle2 className="w-8 h-8 text-accent" />
          </div>
          <h1 className="text-2xl font-bold text-foreground">Password updated</h1>
          <p className="text-muted-foreground text-sm">
            Your password has been changed successfully. You can now sign in using your new password.
          </p>
        </div>
        <Button className="w-full" onClick={() => navigate("/auth", { replace: true })}>
          Back to login
        </Button>
      </>,
    );
  }

  // ── New password form ────────────────────────────────────────────────────
  if (mode === "recover") {
    return shell(
      <>
        <div className="text-center space-y-2">
          <img src={owlMascot} alt="Aras A+" className="w-16 h-16 mx-auto" />
          <h1 className="text-2xl font-bold text-foreground">Reset your password</h1>
          <p className="text-muted-foreground text-sm">
            Choose a new password for your Aras A+ account.
          </p>
        </div>

        <form onSubmit={handleUpdatePassword} className="space-y-4" noValidate>
          <div className="space-y-2">
            <Label htmlFor="new-password">New password</Label>
            <div className="relative">
              <Input
                id="new-password"
                type={showPassword ? "text" : "password"}
                autoComplete="new-password"
                placeholder={`At least ${MIN_PASSWORD_LENGTH} characters`}
                value={password}
                onChange={(e) => {
                  const nextPassword = e.target.value;
                  setPassword(nextPassword);
                  setFieldError(
                    confirmPassword && nextPassword !== confirmPassword
                      ? "Passwords do not match."
                      : null,
                  );
                }}
                disabled={isSubmitting}
                aria-invalid={Boolean(fieldError)}
                aria-describedby={fieldError ? "reset-password-error" : undefined}
                required
              />
              <button
                type="button"
                onClick={() => setShowPassword((v) => !v)}
                aria-label={showPassword ? "Hide password" : "Show password"}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
              >
                {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="confirm-password">Confirm new password</Label>
            <div className="relative">
              <Input
                id="confirm-password"
                type={showConfirm ? "text" : "password"}
                autoComplete="new-password"
                placeholder="Re-enter your new password"
                value={confirmPassword}
                onChange={(e) => {
                  const nextConfirmation = e.target.value;
                  setConfirmPassword(nextConfirmation);
                  setFieldError(
                    nextConfirmation && password !== nextConfirmation
                      ? "Passwords do not match."
                      : null,
                  );
                }}
                disabled={isSubmitting}
                aria-invalid={Boolean(fieldError)}
                aria-describedby={fieldError ? "reset-password-error" : undefined}
                required
              />
              <button
                type="button"
                onClick={() => setShowConfirm((v) => !v)}
                aria-label={showConfirm ? "Hide password" : "Show password"}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
              >
                {showConfirm ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
          </div>

          {fieldError && (
            <p id="reset-password-error" role="alert" className="text-sm text-destructive">
              {fieldError}
            </p>
          )}

          <Button type="submit" className="w-full" disabled={!canSubmitNewPassword}>
            {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            {isSubmitting ? "Updating password..." : "Change Password"}
          </Button>
        </form>

        {backToLogin}
      </>,
    );
  }

  // ── Request a reset link ─────────────────────────────────────────────────
  return shell(
    <>
      <div className="text-center space-y-2">
        <img src={owlMascot} alt="Aras A+" className="w-16 h-16 mx-auto" />
        <h1 className="text-2xl font-bold text-foreground">Reset Password</h1>
        <p className="text-muted-foreground text-sm">
          {isSent
            ? "We've sent you a password reset link"
            : "Enter your email and we'll send you a reset link"}
        </p>
      </div>

      {isSent ? (
        <div className="space-y-4 text-center">
          <div className="w-16 h-16 mx-auto rounded-full bg-accent/10 flex items-center justify-center">
            <Mail className="w-8 h-8 text-accent" />
          </div>
          <p className="text-sm text-muted-foreground">
            Check your inbox at <span className="font-medium text-foreground">{email}</span>
          </p>
          <Button variant="outline" className="w-full" onClick={() => setIsSent(false)}>
            Try another email
          </Button>
        </div>
      ) : (
        <form onSubmit={handleRequest} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email address</Label>
            <Input
              id="email"
              type="email"
              autoComplete="email"
              placeholder="student@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>
          <Button type="submit" className="w-full" disabled={isSending}>
            {isSending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Send Reset Link
          </Button>
        </form>
      )}

      {backToLogin}
    </>,
  );
}
